service: slsV165BreakingChange

provider:
  name: aws
  runtime: nodejs12.x
  stackName: SlsV165BreakingChange-${self:provider.stage}
  stage: ${opt:stage}
  region: eu-central-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ssm:GetParameters"
        - "ssm:DescribeParameters"
      Resource: "arn:aws:ssm:#{AWS::Region}:#{AWS::AccountId}:*"

package:
  exclude:
    - .gitignore
    - package-lock.json
    - package.json
    - README.md
    - serverless.yml

functions:
  hello:
    handler: handler.hello

plugins:
  - serverless-pseudo-parameters
