service: serverless-version-1-65-breaking-change

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage}
  region: eu-central-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ssm:GetParameters"
        - "ssm:DescribeParameters"
      Resource: "arn:aws:ssm:#{AWS::Region}:#{AWS::AccountId}:*"

 exclude:
   - .gitignore
   - package-lock.json
   - package.json
   - README.me
   - serverless.yml

functions:
  hello:
    handler: handler.hello

plugins:
  - serverless-pseudo-parameters
