service: slsV165BreakingChange

provider:
  name: aws
  runtime: nodejs12.x
  stackName: SlsV165BreakingChange-${self:provider.stage}
  stage: test-stage
  region: eu-central-1
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:ListBucket'
      Resource:
        Fn::Join:
          - ''
          - - 'arn:aws:s3:::'
            - Ref: ServerlessDeploymentBucket

package:
  exclude:
    - .gitignore
    - package-lock.json
    - package.json
    - README.md
    - serverless.yml

functions:
  hello:
    handler: handler.hello
